spring:
    application:
        name: example-cache
    jackson:
        date-format: yyyy-MM-dd'T'hh:mm:ss.sssZ
        serialization:
            indent-output: true

server:
    context-path: /
    port: 8080

management:
    context-path: /internal

edison:
    gracefulshutdown:
        enabled: false
    status:
        application:
            description: Example service to show how to use edison-core in your microservices
            environment: local
            group: example
            title: Example Cache
        team:
            business-contact: edison-team@example.org
            name: Edison Team
            technical-contact: edison-dev@example.org
    commonProperties:
        - key: key
          value: value
          description: description
        - key: key1
          value: value1
          description: description1

